apiVersion: v1 
kind: Pod
metadata: 
  name: myapp-pod-2
  namespace: default
  labels:
    app: myapp-3
spec:
  containers:
  - name: nginx-container
    image: nginx
---
apiVersion: v1
kind: Service
metadata:
  namespace: default
  labels:
    app: myapp
  name: nginx-svc
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 80
  selector:
    app: myapp-3
  type: ClusterIP
---