pipeline {
    agent any
    environment {
        IMAGE_NAME = "trancosarg/python-app"
        DOCKERHUB_CREDS = credentials('dockerhub')
    }

    stages {
        stage('Build image') {
            steps {
                sh 'docker build -t ${IMAGE_NAME}:${BUILD_NUMBER} ./python-app'
            }
        }
        stage("Docker login") {
            steps {
                sh 'echo ${DOCKERHUB_CREDS_PSW} | docker login -u ${DOCKERHUB_CREDS_USR} --password-stdin'
            }
        }

        stage("Docker push") {
            steps {
                sh 'docker push ${IMAGE_NAME}:${BUILD_NUMBER}'
            }
        }

        stage("Deploy kubernetes") {
            steps {
                sh 'kubectl set image -f python-app/python-app.yaml python-app=python-app:${BUILD_NUMBER} --local -o yaml > python-app-deploy.yaml'
                sh 'kubectl apply python-app-deploy.yaml'
            }
        }
    }


        post {
            success {
                echo "Docker Push correcto!"
            }
            always {
                sh 'docker logout'
            }
        }  
}

