apiVersion: v1
kind: Namespace
metadata:
  name: eduit
---
apiVersion: v1
kind: Pod
metadata:
  name: "python-app"
  namespace: eduit
  labels:
    app: "python-app"
spec:
  containers:
  - name: python-app
    image: "trancosarg/python-app:0.1"
    resources:
      limits:
        cpu: 200m
        memory: 500Mi
      requests:
        cpu: 100m
        memory: 200Mi
    ports:
    - containerPort: 5000
      name: http
    livenessProbe:
      httpGet:
        path: /ping
        port: http
      initialDelaySeconds: 5
      periodSeconds: 5
    readinessProbe:
      httpGet:
        path: /ping
        port: http
      initialDelaySeconds: 30
      periodSeconds: 5
      timeoutSeconds: 5
    volumeMounts:
    - name: localtime
      mountPath: /etc/localtime
  volumes:
    - name: localtime
      hostPath:
        path: /usr/share/zoneinfo/America/Buenos_Aires
  restartPolicy: Always
---
