# Configuración de la máquina virtual usando Vagrant, versión 2.
Vagrant.configure("2") do |config|

  # Selecciona la caja base para la máquina virtual.
  config.vm.box = "ubuntu/focal64"

  # Define un nombre para la máquina virtual (puede ser cualquier nombre deseado).
  config.vm.define "poc"

  # Ejecuta un comando de shell para obtener la interfaz de red predeterminada.
  # Esto asigna el valor de la interfaz a la variable $default_network_interface.
  $default_network_interface = `ip route | awk '/^default/ {printf "%s", $5; exit 0}'`

  # Configura una interfaz de red pública para la máquina virtual con una dirección IP específica.
  # Utiliza el valor de $default_network_interface para el puente de red.
  config.vm.network "public_network", ip:"10.0.2.16", bridge: "#$default_network_interface"

  # Configura proveedores específicos para la máquina virtual, en este caso, VirtualBox.
  config.vm.provider "virtualbox" do |v|
    # Asigna 512 MB de memoria RAM a la máquina virtual.
    v.memory = 512
    # Asigna 1 núcleos de CPU a la máquina virtual.
    v.cpus = 1
  end

  # Asigna un nombre de host a la máquina virtual.
  config.vm.hostname = "poc"
  
  config.vm.provision :shell, path: "bootstrap.sh"

end