---
- name: Ejemplo de uso de variables de entorno en Ansible
  hosts: servidor_remoto
  tasks:
    - name: Configurar la contrase単a de la base de datos
      shell: |
        # Utiliza la variable de entorno DB_PASSWORD
        echo "Contrase単a de la base de datos: $DB_PASSWORD"
      register: resultado_comando

    - name: Realizar alguna tarea con la contrase単a
      debug:
        msg: "Realizando alguna tarea con la contrase単a: {{ resultado_comando.stdout }}"

        ---
    - name: Ejemplo de uso de variable de entorno del sistema de control
      hosts: servidor_remoto
      tasks:
        - name: Mostrar el valor de la variable de entorno del sistema de control
          debug:
            var: ansible_env.MI_VARIABLE_ENTORNO